apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
      component: server
  serviceName: consul
  podManagementPolicy: "Parallel"
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
        component: server
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      serviceAccountName: consul
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-azu01-c03.uz.kuleuven.ac.be
            weight: 100
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-azu01-i01.uz.kuleuven.ac.be
            weight: 50
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-azu01-i02.uz.kuleuven.ac.be
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-azu01-i01.uz.kuleuven.ac.be
                - osclu-azu01-i02.uz.kuleuven.ac.be
                - osclu-azu01-c03.uz.kuleuven.ac.be
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - consul
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
        runAsUser: 100
      initContainers:
      - command:
        - sh
        - -c
        - if [ -f "/tmp/consul/node" ]; then until grep "^node=${HOSTNAME}\$" /tmp/consul/node;
          do echo "im not on the right host, kill me"; sleep 2; done; else echo "init
          bootstrap"; fi
        image: busybox
        name: init-consul
        volumeMounts:
        - mountPath: /tmp/consul
          name: data
      containers:
        - name: consul
          image: "docker-registry.default.svc:5000/sno-jvvoor1/uzl-consul:1.4.2"
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-encryption-key
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bootstrap-expect=3"
            - "-config-file=/etc/consul/config/server.json"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
          volumeMounts:
            - name: data
              mountPath: /consul/data
            - name: config
              mountPath: /etc/consul/config
            - name: tls
              mountPath: /etc/tls
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              hostPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
      volumes:
        - name: config
          configMap:
            name: consul
        - name: tls
          secret:
            secretName: consul  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1014Mi
