apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
      component: server
  serviceName: consul
  podManagementPolicy: "Parallel"
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
        component: server
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      serviceAccountName: consul
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-pew01-c03.uz.kuleuven.ac.be
            weight: 100
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-pew01-i01.uz.kuleuven.ac.be
            weight: 50
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-pew01-i02.uz.kuleuven.ac.be
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - osclu-pew01-i01.uz.kuleuven.ac.be
                - osclu-pew01-i02.uz.kuleuven.ac.be
                - osclu-pew01-c03.uz.kuleuven.ac.be
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - consul
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
        runAsUser: 100
      containers:
        - name: consul
          image: "docker-registry.default.svc:5000/sno-jvvoor1/uzl-consul:1.4.2"
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-encryption-key
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bootstrap-expect=3"
            - "-config-file=/etc/consul/config/server.json"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-advertise-wan=$(MY_NODE_IP)"
          volumeMounts:
            - name: data
              mountPath: /consul/data
            - name: config
              mountPath: /etc/consul/config
            - name: tls
              mountPath: /etc/tls
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
              protocol: TCP
            - containerPort: 8400
              name: alt-port
              protocol: TCP
            - containerPort: 53
              name: udp-port
              protocol: TCP
            - containerPort: 8443
              name: https-port
              protocol: TCP
            - containerPort: 8080
              name: http-port
              protocol: TCP
            - containerPort: 8301
              name: serflan-tcp
              protocol: TCP
            - containerPort: 8301
              name: serflan-udp
              protocol: UDP
            - containerPort: 8302
              hostPort: 8302
              name: serfwan-tcp
              protocol: TCP
            - containerPort: 8302
              hostPort: 8302
              name: serfwan-udp
              protocol: UDP
            - containerPort: 8600
              name: consuldns
              protocol: TCP
            - containerPort: 8300
              name: server
              hostPort: 8300
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: consul
        - name: tls
          secret:
            secretName: consul  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1014Mi
