kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv-d47cced9
  labels:
    storage-label: data-consul-0
    type: local
spec:
  storageClassName: vmdisk
  capacity:
    storage: 1014Mi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/local-storage/vmdisk/consul
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - osclu-azu01-i01.uz.kuleuven.ac.be
  persistentVolumeReclaimPolicy: Retain
