kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-consul-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data0"
