kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-consul-2
spec:
  storageClassName: vmdisk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1014Mi
  selector:
    matchLabels:
      storage-label: data-consul-2
      type: local
